# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'admin_class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin_student',
            },
        ),
    ]
