# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clazz',
            options={'verbose_name_plural': '\u73ed\u7ea7\u8868'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '\u5b66\u751f\u8868'},
        ),
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Clazz', verbose_name='\u6240\u5c5e\u73ed\u7ea7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clazz',
            name='cname',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u73ed\u7ea7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=30, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u5b66\u53f7'),
        ),
    ]
