# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=30)),
                ('gdesc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('count', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('gimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
