# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('download_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 't_movie',
                'managed': False,
            },
        ),
    ]
