# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'zlt_course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('course', models.ManyToManyField(to='student3.Course')),
            ],
            options={
                'db_table': 'zlt_student3',
            },
        ),
    ]
